

role_words = [
 'manager',
    'copywriter'
    'driver',
 'engineer',
'student',   
    'account excutive',
    'recruiter',
    'enterpreneur',
    'head of digital',
    'product owner',
    'chief',
    'seller',
    'co-Founder',
    'partner',
    'cofounder',
    'coach',
    'founder',
    'recruitment',
    'chief technology',
    'webmaster',
    'commercial',
    'psychologist',
    'head Of Marketing',
    'director',
    'head of human resources',
    'communication',
    'analyst',
    'specialist',
    'directeur',
    'entrepreneur',
    'coo',
    'president',
    'expert',
 'assistant',
 'accountant',
 'administrator',
 'developer',
 'analyst',
 'controller',
 'teacher',
 'consultant',
 'advisor',
 'cleaner',
 'officer',
    'web designer',
    'coordinator',
    'expert',
    'advisor',
    'trainings',
    'training',
    'specialist',
    'officer',
    'trainer',
    'managing',
    'independent contractor',
    'partnerdirector',
    'investment solutions',
 'worker',
 'nurse',
 'operative',
 'surveyor',
 'technician',
 'clerk',
 'chef',
 'director',
 'coordinator',
 'supervisor',
 'partner',
 'labourer',
 'secretary',
 'receptionist',
 'buyer',
 'planner',
 'designer',
 'estimator',
 'leader',
 #'partie', # Part of chef de partie, specific title
 'solicitor',
 'driver',
 'auditor',
 'electrician',
 'negotiator',
 'fitter',
 'operator',
 'turner',
 #'workers', # Plural of worker
 'representative',
 'handler',
 'machinist',
 'miller',
 'welder',
 'inspector',
 'associate',
 #'pa', # Acronym
 'therapist',
 'architect',
 # 'dba', # Acronym
 'bookkeeper',
 'programmer',
 'control', # Is "Quality Control" and "Quality controller" the same thing?
 'telesales', #s', # This is a linguistic exception; telesalesperson?
 'resourcer',
 #'sales', # This is often a role, but is problematic
 'merchandiser',
 #'rgn', # Acronym
 'bricklayer',
 'toolmaker',
 'groundworker',
 # 'finance', # This needs to be part of a role, doesn't make sense by itself
 'cook',
 'optometrist',
 'cashier',
 'paraplanner',
 'author',
 'agent',
 # 'marketing',
 'paralegal',
 'trainer',
 'fellow',
 #'service', # customer service
 'fundraiser',
 'technologist',
 'carpenter',
 'joiner',
 'plumber',
 'caretaker',
 'housekeeper',
 'telemarketer',
 'ledger',
 'studentship',
 # 'english', # e.g. teacher of english
 'guard',
 #'receptionist/administrator', # Two roles
 'plasterer',
 'porter',
 'writer',
 'headteacher', # A contraction of head teacher?
 'conveyancer',
 #'operatives', # plural of operatives
 'physiotherapist',
 'wirer',
 'draughtsperson',
 'support',
 # '(rgn)', # see rgn
 'payroller',
 'chemist',
 'tester',
 # 'hr', # acronym human resources, which is itself an exception
 'generator',
 # 'drivers', # plural of driver
 # 'operations', # Work type
 'underwriter',
 # 'cleaners', # Plural of cleaner
 # 'welder/fabricator', Two titles
 'carer',
 'typist',
 # 'rmn', # Acronym
 #'executives', # Plural
 'picker',
 'specialist',
 # 'assistants', #plural
 # 'payroll', # This is an edge case...
 # 'payable', # Accounts payable, a deparment
 'sprayer',
 # 'teachers', #plural of teacher
 'dentist',
 #'draughtsman', # plural draughtsmen, variant of draughtsperson
 # 'nqt', # Acronym
 # 'adviser', # Variant of advisor
 'practitioner',
 # 'consultants', # Plural of consultants
 'copywriter',
 # 'nurses' # Plural of nurse
'ceo',
'cto',
    'co founder',
    'cfo',
    'chief executive officer',
    'hr',
    'recruiter',
    'consultant',
'cofondateur',   
  # New
  'pharmacist',
  'doctor',
  'lead',
  'radiographer',
    'midwife', # plural midwives?
    'photographer',
'hygenist',
'borer',
'sister',
'surgeon',
'statistician',
'lawyer',
'assessor',
'lecturer',
'staff', # too broad?
    'scientist', 
    'tutor', 
    'nanny', # plural nannies 
    'instructor',
    'executive',
     'marketing',
    'conseil',
    'growth',
    'talent hunter',
    'talent scout',
    'fondateur',
    'fondatrice',
    'master',
    'ingénieure',
    'contractor',
    'talented hunter',
    'business development',
    'consultor',
    'search',
    'project management',
    'psychotherapist',
    'cameraman',
    'sophrologist',
    'seo',
    'independent',
    'owner',
    'gérant',
    'development',
    'ceoowner',
    'human resources',
    'coowner',
    'artist',
    'coaching',
    'producer',
    'supporter',
    'ambassador',
    'cofounderowner',
    'business develop' 
]